name: ensaio
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.13
  - pip
  - make
  # Run
  - pooch>=1.5.0
  # Build
  - python-build
  - twine
  # Test
  - pytest
  - pytest-cov
  - coverage
  # Documentation
  - sphinx==7.2.*
  - sphinx-book-theme==1.1.*
  - sphinx-gallery==0.15.*
  - sphinx-design==0.5.*
  - jupyter-sphinx==0.5.*
  - numpy
  - pandas
  - xarray
  - netcdf4
  - pygmt==0.11.0
  - gmt==6.5.0
  - ipython
  # Style
  - ruff
  - zizmor
  - pip:
    - burocrata
