name: ensaio
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - pip
  - make
  # Run
  - pooch>=1.5.0
  # Build
  - build
  - twine
  # Test
  - pytest
  - pytest-cov
  - coverage
  # Documentation
  - sphinx==7.2.*
  - sphinx-book-theme==1.1.*
  - sphinx-gallery==0.15.*
  - sphinx-design==0.5.*
  - jupyter-sphinx==0.5.*
  - numpy
  - pandas
  - xarray
  - netcdf4
  - pygmt==0.11.0
  - gmt==6.5.0
  - ipython
  # Style
  - black
  - pathspec
  - isort
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-functions
  - flake8-mutable
  - flake8-rst-docstrings
  - flake8-simplify
  - flake8-unused-arguments
  - pep8-naming
  - pip:
    - burocrata
