name: ensaio
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - make
  # Run
  - pooch>=1.5.0
  # Build
  - setuptools_scm>=6.2
  - setuptools>=45
  - wheel
  - twine
  # Documentation
  - sphinx==3.5.*
  - sphinx-book-theme==0.1.*
  - sphinx-gallery==0.10.*
  - pygmt
  # Test
  - pytest
  - pytest-cov
  - coverage
  # Style
  - black
  - pathspec
  - isort
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-functions
  - flake8-mutable
  - flake8-rst-docstrings
  - flake8-simplify
  - pep8-naming
  - pip:
    # Install flake8-unused-arguments through pip
    # (not available through conda yet)
    - flake8-unused-arguments
